const services=[['✧','صيانة التكييفات','نرجّع تكييفك لأفضل أداء بأيدي فنيين متخصصين.'],['⌂','تركيب التكييفات','تركيب احترافي يضمن لك كفاءة أعلى وعمرًا أطول.'],['✦','تنظيف التكييفات','تنظيف عميق يحسن جودة الهواء ويوفر في استهلاك الطاقة.'],['⌁','كشف الأعطال','تشخيص دقيق للمشكلة قبل البدء بأي إصلاح.'],['◌','شحن الفريون','شحن آمن وفحص كامل لدورة التبريد.'],['◷','الصيانة الدورية','خطط متابعة تحافظ على كفاءة تكييفك طوال العام.']];
const reviews=[['م','محمد السيد','"الفني وصل في الموعد بالضبط، وشخّص المشكلة بسرعة. تجربة محترمة جدًا من أول مكالمة."'],['س','سارة أحمد','"أخيرًا لقيت خدمة تكييف مريحة وواضحة. السعر كان زي ما اتفقنا والخدمة ممتازة."'],['ع','عمر خالد','"طلبت تنظيف وتركيب في نفس اليوم. المتابعة كانت ممتازة والفني فاهم جدًا."']];
const seedOrders=[{id:'NS-260909-4821',name:'أحمد محمود',phone:'01225775453',area:'مدينة نصر، القاهرة',service:'صيانة التكييفات',date:'2026-09-09T14:30',status:3,address:'شارع الطيران، برج 12، الدور الرابع',acType:'سبليت',description:'التكييف لا يبرد بشكل كاف'}];
const state={page:'home',reviewIndex:0,orders:JSON.parse(localStorage.getItem('nesora_orders')||'null')||seedOrders,technicians:JSON.parse(localStorage.getItem('nesora_technicians')||'[]'),admin:sessionStorage.getItem('nesora_admin')==='true'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('nesora_orders',JSON.stringify(state.orders));localStorage.setItem('nesora_technicians',JSON.stringify(state.technicians))}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function route(page){if(page==='admin'&&!state.admin){$('#loginModal').hidden=false;return}state.page=page;$$('[data-page]').forEach(el=>el.hidden=el.dataset.page!==page);window.scrollTo({top:0,behavior:'smooth'});if(page==='admin')renderAdmin();if(page==='home')renderHome();if(location.hash!==`#${page}`)history.pushState({},'',`#${page}`);$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===page))}
function renderHome(){if($('#serviceGrid').children.length)return;$('#serviceGrid').innerHTML=services.map((s,i)=>`<article class="service-card"><div class="service-icon">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p><a href="#request" data-route="request" data-service="${s[1]}">اطلب الخدمة ←</a></article>`).join('');renderReviews();$('#serviceSelect').innerHTML='<option value="">اختر الخدمة</option>'+services.map(s=>`<option>${s[1]}</option>`).join('');$$('[data-service]').forEach(a=>a.addEventListener('click',()=>{setTimeout(()=>{$('#serviceSelect').value=a.dataset.service},0)}))}
function renderReviews(){const shown=[0,1,2].map(i=>reviews[(state.reviewIndex+i)%reviews.length]);$('#reviewGrid').innerHTML=shown.map(r=>`<article class="review-card"><span class="stars">★★★★★</span><blockquote>${r[2]}</blockquote><div class="review-person"><span class="review-avatar">${r[0]}</span><div><b>${r[1]}</b><small>عميل موثّق · منذ أسبوع</small></div></div></article>`).join('')}
function generateId(){const d=new Date(),date=String(d.getFullYear()).slice(2)+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0');return `NS-${date}-${Math.floor(1000+Math.random()*9000)}`}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function openWhatsApp(message){window.open(`https://wa.me/201225775453?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
function submitService(e){e.preventDefault();const data=formData(e.target);const order={...data,id:generateId(),status:0,createdAt:new Date().toISOString()};state.orders.unshift(order);save();openWhatsApp(`طلب خدمة جديد من موقع NESORA\n\nرقم الطلب: ${order.id}\nالاسم: ${order.name}\nالهاتف: ${order.phone}\nالمنطقة: ${order.area}\nالعنوان: ${order.address}\nالخدمة: ${order.service}\nنوع التكييف: ${order.acType}\nالموعد: ${order.date}\nوصف المشكلة: ${order.description}`);e.target.reset();toast(`تم استلام طلبك بنجاح · رقم الطلب ${order.id}`);setTimeout(()=>route('track'),650);setTimeout(()=>{const input=$('#trackForm input[name="orderId"]');if(input)input.value=order.id},700)}
function submitJoin(e){e.preventDefault();const data=formData(e.target);const technician={...data,id:`TECH-${Date.now().toString().slice(-5)}`,status:'جديد'};state.technicians.unshift(technician);save();openWhatsApp(`طلب انضمام فني جديد إلى NESORA\n\nرقم الطلب: ${technician.id}\nالاسم: ${technician.name}\nالهاتف: ${technician.phone}\nالمنطقة: ${technician.area}\nالتخصص: ${technician.specialty}\nسنوات الخبرة: ${technician.years}\nالخدمات: ${technician.services}`);e.target.reset();toast('تم استلام طلبك وسيتم مراجعته من فريق NESORA.');setTimeout(()=>route('home'),1100)}
function statusLabel(status){return ['تم استلام الطلب','جاري المراجعة','تم تعيين الفني','الفني في الطريق','جاري تنفيذ الخدمة','تم إتمام الطلب'][status]||'تم استلام الطلب'}
function renderTrack(order){const steps=['تم استلام الطلب','جاري المراجعة','تم تعيين الفني','الفني في الطريق','جاري تنفيذ الخدمة','تم إتمام الطلب'];return `<article class="order-card"><div class="order-head"><div><small>رقم الطلب</small><h2>${order.id}</h2></div><span class="order-status">${statusLabel(order.status)}</span></div><div class="progress-track">${steps.map((s,i)=>`<div class="progress-step ${i<=order.status?'done':''}"><i>${i<=order.status?'✓':i+1}</i><span>${s}</span></div>`).join('')}</div><div class="order-meta"><div><small>نوع الخدمة</small><strong>${order.service}</strong></div><div><small>تاريخ الطلب</small><strong>${new Date(order.createdAt||order.date).toLocaleDateString('ar-EG')}</strong></div><div><small>المنطقة</small><strong>${order.area}</strong></div></div>${order.technician?`<div class="technician-box">الفني المعين: <b>${order.technician}</b> · سيتواصل معك قبل الوصول.</div>`:''}</article>`}
function submitTrack(e){e.preventDefault();const d=formData(e.target),order=state.orders.find(o=>o.id.toLowerCase()===d.orderId.trim().toLowerCase()&&o.phone===d.phone);$('#trackResult').innerHTML=order?renderTrack(order):`<div class="order-card"><h3>لم نعثر على طلب مطابق</h3><p style="color:var(--muted);font-size:12px;margin-top:8px">تأكد من رقم الطلب ورقم الهاتف، أو تواصل معنا عبر WhatsApp للمساعدة.</p></div>`}
function renderAdmin(){const total=state.orders.length,newOrders=state.orders.filter(o=>o.status<2).length,active=state.orders.filter(o=>o.status>=2&&o.status<5).length,done=state.orders.filter(o=>o.status===5).length;$('#adminContent').innerHTML=`<div class="admin-stat-grid"><div class="admin-stat"><span>إجمالي الطلبات</span><strong>${total}</strong><i>↑ 12% هذا الشهر</i></div><div class="admin-stat"><span>طلبات جديدة</span><strong>${newOrders}</strong><i>تحتاج مراجعة</i></div><div class="admin-stat"><span>قيد التنفيذ</span><strong>${active}</strong><i>متابعة مباشرة</i></div><div class="admin-stat"><span>الفنيون المقبولون</span><strong>${state.technicians.filter(t=>t.status==='مقبول').length}</strong><i>${state.technicians.length} طلبات مسجلة</i></div></div><div class="admin-columns"><section class="admin-panel"><h3>آخر الطلبات</h3><table class="admin-table"><thead><tr><th>رقم الطلب</th><th>العميل</th><th>الخدمة</th><th>الحالة</th></tr></thead><tbody>${state.orders.map((o,i)=>`<tr><td><b>${o.id}</b></td><td>${o.name}</td><td>${o.service}</td><td><select data-order-status="${i}">${['تم الاستلام','قيد المراجعة','تم التعيين','في الطريق','قيد التنفيذ','مكتمل'].map((s,n)=>`<option value="${n}" ${o.status===n?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="4">لا توجد طلبات بعد</td></tr>'}</tbody></table></section><section class="admin-panel"><h3>طلبات انضمام جديدة</h3>${state.technicians.length?state.technicians.map((t,i)=>`<div style="border-bottom:1px solid var(--line);padding:10px 0;font-size:11px"><b>${t.name}</b><span style="display:block;color:var(--muted)">${t.specialty} · ${t.area} · ${t.years} سنوات</span><select data-tech-status="${i}" style="margin-top:6px"><option ${t.status==='جديد'?'selected':''}>جديد</option><option ${t.status==='مقبول'?'selected':''}>مقبول</option><option ${t.status==='مرفوض'?'selected':''}>مرفوض</option></select></div>`).join(''):'<p style="font-size:12px;color:var(--muted)">لا توجد طلبات انضمام جديدة.</p>'}</section></div>`;$$('[data-order-status]').forEach(el=>el.addEventListener('change',e=>{state.orders[+e.target.dataset.orderStatus].status=+e.target.value;save();renderAdmin();toast('تم تحديث حالة الطلب')}));$$('[data-tech-status]').forEach(el=>el.addEventListener('change',e=>{state.technicians[+e.target.dataset.techStatus].status=e.target.value;save();renderAdmin();toast('تم تحديث حالة الفني')}))}
function init(){renderHome();const hash=location.hash.replace('#','');if(hash&&['home','request','join','track','admin'].includes(hash))route(hash);document.addEventListener('click',e=>{const link=e.target.closest('[data-route]');if(link){e.preventDefault();const target=link.getAttribute('href')?.slice(1);if(link.dataset.route==='home'&&['services','process','reviews'].includes(target)){route('home');setTimeout(()=>document.getElementById(target)?.scrollIntoView({behavior:'smooth'}),0)}else{route(link.dataset.route)}$('#desktopNav').classList.remove('mobile-open');$('#menuToggle').setAttribute('aria-expanded','false')}});$('#serviceForm').addEventListener('submit',submitService);$('#joinForm').addEventListener('submit',submitJoin);$('#trackForm').addEventListener('submit',submitTrack);$('#nextReview').addEventListener('click',()=>{state.reviewIndex=(state.reviewIndex+1)%reviews.length;renderReviews()});$('#prevReview').addEventListener('click',()=>{state.reviewIndex=(state.reviewIndex+reviews.length-1)%reviews.length;renderReviews()});$('#menuToggle').addEventListener('click',()=>{const nav=$('#desktopNav'),isOpen=nav.classList.toggle('mobile-open');$('#menuToggle').setAttribute('aria-expanded',String(isOpen));$('#menuToggle').setAttribute('aria-label',isOpen?'إغلاق القائمة':'فتح القائمة')});document.addEventListener('click',e=>{if(!e.target.closest('.topbar')&&!e.target.closest('#desktopNav')){$('#desktopNav').classList.remove('mobile-open');$('#menuToggle').setAttribute('aria-expanded','false')}});$('#closeLogin').addEventListener('click',()=>$('#loginModal').hidden=true);$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const d=formData(e.target);if(d.email==='admin@nesora.co'&&d.password==='nesora2026'){state.admin=true;sessionStorage.setItem('nesora_admin','true');$('#loginModal').hidden=true;route('admin');toast('مرحبًا بك في لوحة الإدارة')}else toast('بيانات الدخول غير صحيحة')});$('#logoutBtn').addEventListener('click',()=>{state.admin=false;sessionStorage.removeItem('nesora_admin');route('home');toast('تم تسجيل الخروج')})}
init();
